<?php
require_once('../server/configDB.php'); // Ganti dengan path yang sesuai
require_once('../lib/TCPDF/tcpdf.php'); // Ganti dengan path yang sesuai

// Buat objek TCPDF
$pdf = new TCPDF();

// Set informasi dokumen
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Your Name');
$pdf->SetTitle('Laporan Inventaris Tersedia');
$pdf->SetSubject('Laporan Inventaris');
$pdf->SetKeywords('TCPDF, PDF, laporan, inventaris');

// Set header dan footer
$pdf->setHeaderData('', 0, 'Laporan Inventaris Tersedia', 'Generated by Your Name');
$pdf->setHeaderFont(array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));
$pdf->setPrintHeader(true);
$pdf->setPrintFooter(true);

// Set ukuran dan orientasi halaman
$pdf->AddPage();

// Set font
$pdf->SetFont('helvetica', '', 12);

// Query untuk mengambil data inventaris yang tersedia
$query = "SELECT i.*, d.nama_departemen, k.nama_kategori 
          FROM inventaris i 
          JOIN departemen d ON i.id_departemen = d.id_departemen 
          JOIN kategori k ON i.id_kategori = k.id_kategori 
          WHERE i.jumlah_akhir > 0";

$result = mysqli_query($conn, $query);

// Buat tabel
$html = '<h2>Laporan Inventaris Tersedia</h2>';
$html .= '<table border="1" cellpadding="4">
            <thead>
                <tr style="background-color: #f2f2f2; font-weight: bold; text-align: center;">
                    <th>No</th>
                    <th>Kode Inventaris</th>
                    <th>Departemen</th>
                    <th>Kategori</th>
                    <th>Nama Barang</th>
                    <th>Jumlah Awal</th>
                    <th>Jumlah Akhir</th>
                    <th>Satuan</th>
                </tr>
            </thead>
            <tbody>';

$no = 1;
while ($row = mysqli_fetch_assoc($result)) {
    $html .= '<tr style="text-align: center;">
                <td>' . $no++ . '</td>
                <td>' . $row['kode_inventaris'] . '</td>
                <td>' . $row['nama_departemen'] . '</td>
                <td>' . $row['nama_kategori'] . '</td>
                <td>' . $row['nama_barang'] . '</td>
                <td>' . $row['jumlah_awal'] . '</td>
                <td>' . $row['jumlah_akhir'] . '</td>
                <td>' . $row['satuan'] . '</td>
              </tr>';
}

$html .= '</tbody></table>';

// Output HTML content
$pdf->writeHTML($html, true, false, true, false, '');

// Close and output PDF document
$pdf->Output('laporan_inventaris_tersedia.pdf', 'I');
?>